config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get 'estamations', :to => 'estamations#index', :as => :estamations
get 'estamations/add', :to => 'estamations#add', :as => :estamation_add
get 'estamations/edit/:id', :to => 'estamations#edit', :as => :estamation_edit
get 'estamations/project/:project_id', :to => 'estamations#index_w_project'
get 'estamations/:id', :to => 'estamations#show', :as => :estamation
post 'estamations', :to => 'estamations#create', :as => :estamation_create
put 'estamations/:id', :to => 'estamations#update', :as => :estamation_update
delete 'estamations/id', :to => 'estamations#destroys', :as => :estamation_delete

get 'estamations/:id/entry/new', :to => 'estamation_entry#new', :as => :new_estamation_entry
post 'estamations/:estamation_id/entry', :to => 'estamation_entry#create', :as => :estamation_entry_create

get 'projects/:project_id/estamations', :to => 'estamations#index_w_project', :as => :project_estamations

get 'projects/:project_id/estamations/:id', :to => 'estamations#show', :as => :project_estamation

app/models/estamation.rb
class Estamation < ActiveRecord::Base
  unloadable
  belongs_to :estamation_status
  belongs_to :issue_priority
  belongs_to :project
  belongs_to :user
  has_and_belongs_to_many :estamation_groups
  has_many :estamation_entries
  
  acts_as_attachable :after_add => :attachment_added, :after_remove => :attachment_removed
  acts_as_watchable
  acts_as_searchable :columns => ['title', "#{table_name}.description"]
  after_create :send_notification           

    def editable?
        return true if User.current.id == self.user_id
        return true if User.current.admin?
        return false
    end
    
    def entryble?
        return true if self.watcher_users.include? User.current
        return true if User.current.admin?
        return true if self.editable?
        return false
    end
    
    def send_notification
        EstamationMailer.deliver_estamation_add(self)
    end
    
end

app/controllers/estamations_controller.rb
class EstamationsController < ApplicationController
  #unloadable
  
  helper :watchers
  include WatchersHelper
  helper :issues
  include IssuesHelper
  helper :attachments
  include AttachmentsHelper
  
  def index
    if params[:project_id].nil?
      @estamations = Estamation.all
    else
      logger.debug(params)
      @project = Project.find(params[:project_id])
      @estamations = Estamation.where({project_id: @project.id}).all
    end

  end
  
  def index_w_project
  end
  
  def add
      @estamation = Estamation.new
      @estamation.user_id = User.current.id
      @available_watchers = (User.all.sort + @estamation.watcher_users).uniq
      @projects = ([Project.new] + Project.active).uniq
  end

  def edit
      set_estamation
      @available_watchers = (User.all.sort + @estamation.watcher_users).uniq
      @projects = ([Project.new] + Project.active).uniq
  end
  
  def show
      set_estamation
      @newentry = @estamation.estamation_entries.new
      @newentry.user_id = User.current.id
  end

  def create
      @estamation = Estamation.new(params[:estamation])
      @estamation.save_attachments(params[:attachments] || (params[:estamation] && params[:estamation][:uploads]))
      
      respond_to do |format|
        if @estamation.save
          format.html {
              flash[:notice] = l(:notice_estamation_successful_create, :id => view_context.link_to("##{@estamation.id}", estamation_path(@estamation), :title => @estamation.title))
              unless @estamation.project.nil?
                attrs = {}
                redirect_to project_estamation_path(@estamation.project, @estamation)
              else
                redirect_to estamation_path(@estamation)
              end
          }
          format.json { render action: 'show', status: :created, location: @estamation }
        else
          format.html { render action: 'add' }
          format.json { render json: @estamation.errors, status: :unprocessable_entity }
        end
      end
  end
  
  def update
      set_estamation
      @estamation.save_attachments(params[:attachments] || (params[:estamation] && params[:estamation][:uploads]))
      respond_to do |format|
        if @estamation.update_attributes(params[:estamation])
          format.html {
              flash[:notice] = l(:notice_estamation_successful_updated, :id => view_context.link_to("##{@estamation.id}", estamation_path(@estamation), :title => @estamation.title))
              unless @estamation.project.nil?
                redirect_to project_estamation_path(@estamation.project, @estamation)
              else
                redirect_to estamation_path(@estamation)
              end
          }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @estamation.errors, status: :unprocessable_entity }
        end
      end
  end

  def change_status
  end
  
  private
  def set_estamation
      if params[:project_id].nil?
          @estamation = Estamation.find(params[:id])
      else
        @project = Project.find(params[:project_id])
          @estamation = Estamation.where({:id => params[:id], :project_id => @project.id}).first
      end
  end
end

app/helpers/estamations_helper.rb
module EstamationsHelper
    def get_estamation_path(estamation)
        unless estamation.project.nil?
            return project_estamation_path(estamation.project.id, estamation.id)
        else
            return estamation_path(estamation.id)
        end
    end
end

app/views/estamations/_action_menu.html.erb
<div class="contextual">
<%= link_to l(:button_update), estamation_edit_path(@estamation), :onclick => 'showAndScrollTo("update", "estamation_notes"); return false;', :class => 'icon icon-edit', :accesskey => accesskey(:edit) if @estamation.editable? %>
<%= watcher_link(@estamation, User.current) %>
<%= link_to l(:button_delete), estamation_path(@estamation), :data => {:confirm => l(:text_estamations_destroy_confirmation)}, :method => :delete, :class => 'icon icon-del' if @estamation.editable? %>
</div>

app/views/estamations/_form.html.erb
<%= labelled_fields_for :estamation, @estamation do |f| %>
  <%= f.hidden_field :user_id %>
  <p>
    <%= f.text_field :title, :required => true %>
  </p>
  <p>
    <%= f.label_for_field :description %>
    <%= content_tag 'span', :id => "estamation_description_and_toolbar" do %>
      <%= f.text_area :description,
                     :cols => 60,
                     :rows => (@estamation.description.blank? ? 10 : [[10, @estamation.description.length / 50].max, 100].min),
                     :accesskey => accesskey(:edit),
                     :class => 'wiki-edit',
                     :no_label => true %>
    <% end %>
    <%= wikitoolbar_for 'estamation_description' %>
  </p>
  <div class="splitcontent">
    <div class="splitcontentleft">
      <% if @estamation.project_id.nil? %>
        <p>
          <%= f.select :project_id, @projects.collect {|t| [t.name, t.id]}, {:required => true} %>
        </p>
      <% end %>
      <p>
        <%= f.select :estamation_status_id, EstamationStatus.all.collect {|t| [t.title, t.id]}, {:required => true} %>
      </p>
      <p>
        <%= f.select :issue_priority_id, IssuePriority.active.collect {|t| [t.name, t.id]}, {:required => true} %>
      </p>
    </div>
    <div class="splitcontentright">
      <% if User.current.id==@estamation.user_id %>
        <p>
          <%= f.text_field :link %>
        </p>
      <% end %>

    
      <p>
        <%= f.text_field :actual_due %>
        <%= calendar_for('estamation_actual_due') %>
      </p>
    </div>
  </div>
  <div>&nbsp;</div>
  <p id="attachments_form">
    <label>
      <%= l(:label_attachment_plural) %>
    </label>
    <%= render :partial => 'attachments/form', :locals => {:container => @issue} %>
  </p>
  <p id="watchers_form">
    <label>
      <%= l(:label_issue_watchers) %>
    </label>
    <span id="watchers_inputs">
      <%= watchers_checkboxes(@estamation, @available_watchers) %>
    </span>
    <span class="search_for_watchers">
      <%= link_to l(:label_search_for_watchers),
              {:controller => 'watchers', :action => 'new', :project_id => @estamation.project},
              :remote => true,
              :method => 'get' %>
    </span>
  </p>

<% end %>

app/views/estamations/add.html.erb
<h2>Add Estamation</h2>

<%= labelled_form_for @estamation, :url => estamation_create_path,
                             :html => {:id => 'estamation-form', :multipart => true} do |f| %>
  <%= error_messages_for 'estamation' %>
  <div class="box tabular">
    <div id="all_attributes">
  <%= render 'estamations/form', :locals => {:f => f} %>
  <%= submit_tag l(:button_create) %>
  <%= submit_tag l(:button_create_and_continue), :name => 'continue' %>
</div>
</div>
<% end %>

<%= javascript_tag "$('#estamation_title').focus();" %>

app/views/estamations/change_status.html.erb
<h2>EstamationsController#change_status</h2>

app/views/estamations/create.html.erb
<h2>EstamationsController#create</h2>

app/views/estamations/edit.html.erb
<h2>Edit Estamation <%= @estamation.title %></h2>

<%= labelled_form_for @estamation, :url => estamation_update_path(@estamation),
                             :html => {:id => 'estamation-form', :multipart => true} do |f| %>
  <%= error_messages_for 'estamation' %>
  <div class="box tabular">
    <div id="all_attributes">
  <%= render 'estamations/form', :locals => {:f => f} %>
  <%= submit_tag l(:button_save) %>
</div>
</div>
<% end %>

<%= javascript_tag "$('#estamation_title').focus();" %>

app/views/estamations/index.html.erb
<% content_for :header_tags do %>
    <%= javascript_include_tag 'initial', :plugin => 'estamation' %>
    <%= stylesheet_link_tag 'estamation_style', :plugin => 'estamation' %>
<% end %>

<div class="contextual">
  <span>
    <%= link_to 'Add New', { :action => 'add' }, :class => 'icon icon-add' %>
  </span>
</div>

<h2>Estamations</h2>

<%= form_tag({}) do -%>
<%= hidden_field_tag 'back_url', url_for(params), :id => nil %>
<div class="autoscroll">

  <table class="list issues">
    <thead>
      <tr>
        <th>&nbsp;</th>
        <th><%= t(:title) %></th>
        <th><%= t(:status)%></th>
        <th><%= t(:user) %></th>
      </tr>
    </thead>
  <% @estamations.each do |estamation| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <td class="id">
        <%= link_to estamation.id, get_estamation_path(estamation) %>
      </td>
      <td class="subject"><%= link_to estamation.title, get_estamation_path(estamation) %></td>
      <td class="status"><%= link_to estamation.estamation_status, get_estamation_path(estamation) %></td>
      <td class="assignied_to"><%= link_to estamation.user.name, get_estamation_path(estamation) %></td>
    </tr>
  <% end %>
  </table>
</div>
<% end -%>

app/views/estamations/show.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'estamation_style', :plugin => 'estamation' %>
<% end %>
<%= render :partial => 'action_menu' %>
<h2><%= t(:Estimate)%> <%= @estamation.id %></h2>

<div class="details">
  <div class="subject">
  <%= @estamation.title %>
  </div>
  <p class="author">
    <%= authoring @estamation.created_at, @estamation.user %>.
    <% if @estamation.created_at != @estamation.updated_at %>
      <%= l(:label_updated_time, time_tag(@estamation.updated_at)).html_safe %>.
    <% end %>
  </p>
  
  <table class="attributes">
  <%= issue_fields_rows do |rows|
    rows.left l(:field_status), h(@estamation.estamation_status), :class => 'status'
    
    if @estamation.editable?
      rows.left l(:field_link), link_to(@estamation.link,@estamation.link), :class => 'link'
    end
    unless @estamation.actual_due.nil?
      rows.right l(:field_actual_due), format_date(@estamation.actual_due), :class => 'actual_due'
    end

  end %>
  </table>
  <% if @estamation.description? || @estamation.attachments.any? -%>
    <hr />
    <% if @estamation.description? %>
    <div class="description">
      <p><strong><%=l(:field_description)%></strong></p>
      <div class="wiki">
      <%= textilizable @estamation, :description, :attachments => @estamation.attachments %>
      </div>
    </div>
    <% end %>
    <%= link_to_attachments @estamation, :thumbnails => true %>
  <% end -%>
</div>
&nbsp;
<% if @estamation.estamation_entries.all.size!=0 %>
  <h3>Entries</h3>
  <% @estamation.estamation_entries.all.each do |estamation_entry| %>
    <div class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <%= render estamation_entry %>
    </div>
  <% end %>
<% end %>

<div class="details">
  <h2>Add Entry</h2>
  <%= form_for [@estamation,@newentry], :url => estamation_entry_create_path(@estamation), :html => {:id => 'estamation-form', :multipart => true} do |f| %>
    <%= render 'estamation_entries/form', :locals => {:f => f} %>
    <%= submit_tag l(:button_create) %>
  <% end %>
</div>